# -*- coding: utf-8 -*-
"""Mcq updated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qq3jgHJ8R1d1Qm_t0QioqmTHQkE-v6cW
"""

import pandas as pd
import os
from io import BytesIO

# Reload the modified MCQ file
file_path = "/content/drive/MyDrive/Python_40_MCQ_Questions_Modified.xlsx" #Changed to use Google Drive path
mcq_df = pd.read_excel(file_path)

# Define the updated results file path
results_file_path = "/content/drive/MyDrive/MCQ_Results_Updated.xlsx" #Changed to use Google Drive path

# Create an updated DataFrame with new columns for level-wise scoring and feedback
updated_results_df = pd.DataFrame(columns=[
    "Reg No.", "Name", "Total Score", "Low Level Score", "Medium Level Score", "High Level Score", "Feedback"
])

# Save the updated format
updated_results_df.to_excel(results_file_path, index=False)

# Provide the updated file path for download
results_file_path

import pandas as pd
import os

csv_file_path = "/content/drive/MyDrive/MCQ_Results_Updated.csv"

# Expected columns
correct_columns = ["Reg No.", "Name", "Score", "Low Level Score", "Medium Level Score", "High Level Score", "Unknown Level Score", "Feedback"]

# Check if the CSV exists
if os.path.exists(csv_file_path):
    try:
        results_df = pd.read_csv(csv_file_path, dtype=str, encoding="utf-8", on_bad_lines="skip")

        # Identify missing columns and add them without deleting data
        missing_columns = [col for col in correct_columns if col not in results_df.columns]
        if missing_columns:
            print(f"⚠️ Adding missing columns: {missing_columns}")
            for col in missing_columns:
                results_df[col] = ""  # Add empty columns

            # Save updated file without deleting old data
            results_df.to_csv(csv_file_path, index=False)
        else:
            print("✅ CSV structure is correct.")

    except pd.errors.ParserError:
        print("⚠️ Error parsing the CSV file. Creating a new one.")
        results_df = pd.DataFrame(columns=correct_columns)
        results_df.to_csv(csv_file_path, index=False)
else:
    print("🆕 Creating a new results file.")
    results_df = pd.DataFrame(columns=correct_columns)
    results_df.to_csv(csv_file_path, index=False)

import pandas as pd
import os

# Define file paths
mcq_file = "/content/drive/MyDrive/Python_40_MCQ_Questions_Modified.xlsx"
student_file = "/content/drive/MyDrive/Kerala_Student_Records_Final.xlsx"
csv_file_path = "/content/drive/MyDrive/MCQ_Results_Updated.csv"

# Define correct headers
expected_columns = ["Reg No.", "Name", "Score", "Low Level Score",
                    "Medium Level Score", "High Level Score", "Unknown Level Score", "Feedback"]

# Ensure CSV file is correctly formatted
if os.path.exists(csv_file_path):
    try:
        results_df = pd.read_csv(csv_file_path, dtype=str, encoding="utf-8", on_bad_lines="skip")

        # Fix column mismatch
        if not all(col in results_df.columns for col in expected_columns):
            print("⚠️ Existing CSV has incorrect columns. Fixing column names.")
            results_df = results_df.reindex(columns=expected_columns, fill_value="")
            results_df.to_csv(csv_file_path, index=False)

        recorded_students = set(results_df["Reg No."].astype(str)) if not results_df.empty else set()

    except pd.errors.ParserError:
        print("⚠️ Error parsing the CSV file. Overwriting with new headers.")
        results_df = pd.DataFrame(columns=expected_columns)
        results_df.to_csv(csv_file_path, index=False)
        recorded_students = set()
else:
    # Create new CSV with correct headers if it doesn't exist
    results_df = pd.DataFrame(columns=expected_columns)
    results_df.to_csv(csv_file_path, index=False)
    recorded_students = set()

# Check if files exist before loading
if not os.path.exists(mcq_file) or not os.path.exists(student_file):
    print("❌ Error: One or more required files are missing!")
    exit()

# Load datasets
mcqs = pd.read_excel(mcq_file)
students = pd.read_excel(student_file)

# Convert to dictionary format
students_dict = students.to_dict(orient="records")
mcqs_dict = mcqs.to_dict(orient="records")

def evaluate_student(Reg_No):
    """Evaluates a student based on their registration number and generates feedback."""
    Reg_No = str(Reg_No).strip()

    # Check if the student has already been recorded
    if Reg_No in recorded_students:
        print("⚠️ Score already recorded for this student!")
        return

    found_student = next((s for s in students_dict if str(s["Reg No."]) == Reg_No), None)
    if not found_student:
        print("❌ Student not found.")
        return

    print(f"\n👨‍🎓 Student: {found_student['Name']}")

    # Score tracking per level
    level_scores = {"Low": 0, "Medium": 0, "High": 0, "Unknown": 0}
    level_totals = {"Low": 0, "Medium": 0, "High": 0, "Unknown": 0}

    for mcq in mcqs_dict:
        level = mcq.get("Level", "Unknown")  # Get level, default to "Unknown"
        level_totals[level] += 1

        print("\n" + mcq["Question"])
        options = [mcq[col] for col in mcq.keys() if "Option" in col]

        for idx, option in enumerate(options, start=1):
            print(f"{idx}. {option}")

        while True:
            try:
                answer_idx = int(input("Enter your choice (1-4): ")) - 1
                if 0 <= answer_idx < len(options):
                    break
                else:
                    print("⚠️ Invalid choice. Enter a number between 1 and 4.")
            except ValueError:
                print("⚠️ Please enter a valid number.")

        try:
            correct_idx = int(str(mcq["Correct Answer"]).strip()) - 1
        except ValueError:
            print("⚠️ Error: Correct answer format is incorrect. Skipping this question.")
            continue

        if answer_idx == correct_idx:
            print("✅ Correct!")
            level_scores[level] += 1
        else:
            print(f"❌ Incorrect! Correct answer: {correct_idx + 1}")

    # Calculate total score
    total_score = sum(level_scores.values())
    total_questions = sum(level_totals.values())
    print(f"\n🎯 Final Score: {total_score}/{total_questions}")

    # Generate feedback
    feedback = []  # Initialize feedback list
    for level in ["Low", "Medium", "High", "Unknown"]:
        if level_totals[level] > 0:
            accuracy = (level_scores[level] / level_totals[level]) * 100
            if accuracy >= 80:
                feedback.append(f"✅ Excellent understanding of {level}-level questions.")
            elif accuracy >= 50:
                feedback.append(f"📘 Good in {level}-level questions but needs improvement.")
            else:
                feedback.append(f"❗ Weak in {level}-level questions. Needs more practice.")

    # Convert feedback list to a single string
    feedback_text = " | ".join(feedback)

    # Ensure all columns exist in the CSV
    if os.path.exists(csv_file_path):
        results_df = pd.read_csv(csv_file_path, dtype=str, encoding="utf-8", on_bad_lines="skip")

        # Check if Feedback column is missing and fix it
        if not all(col in results_df.columns for col in expected_columns):
            print("⚠️ CSV file has incorrect columns. Fixing now...")
            results_df = results_df.reindex(columns=expected_columns, fill_value="")
            results_df.to_csv(csv_file_path, index=False)

    # Create DataFrame with Feedback Column
    new_result = pd.DataFrame([{
        "Reg No.": Reg_No,
        "Name": found_student["Name"],
        "Score": total_score,
        "Low Level Score": level_scores["Low"],
        "Medium Level Score": level_scores["Medium"],
        "High Level Score": level_scores["High"],
        "Unknown Level Score": level_scores["Unknown"],
        "Feedback": feedback_text  # ✅ Now explicitly adding Feedback
    }])

    # Append results while ensuring correct headers
    file_exists = os.path.exists(csv_file_path)
    new_result.to_csv(csv_file_path, mode="a", header=not file_exists, index=False)

    print("\n📂 Score saved successfully!")

# Example Usage
Reg_No = input("Enter Registration Number: ").strip()
evaluate_student(Reg_No)