# -*- coding: utf-8 -*-
"""code assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGZjUKVZY9Aaarvi_VjXifMeC78RxUpk
"""

import pandas as pd
import timeit
import ast
import autopep8
import matplotlib.pyplot as plt
from io import StringIO
import contextlib
import traceback

# Load student responses
file_path = '/content/drive/MyDrive/merged_student_responses.xlsx'
df = pd.read_excel(file_path)

# Expected outputs for reference
expected_outputs = [
    [9, 4, 1],  # Squares of digits
    50,  # Sum of squares
    ['green', 'orange', 'red'],  # Sorted list
    10,  # Minimum cost
    'Node class with data and next pointer'  # Linked list
]

# Function to execute code and capture the last expression's value
def execute_code(response):
    local_vars = {}
    try:
        # Execute the code and capture the last evaluated expression
        exec(response, {}, local_vars)
        # Capture the last variable output
        if local_vars:
            last_var = list(local_vars.values())[-1]
            return last_var, None
        else:
            return None, "No output captured"
    except Exception as e:
        # Capture the entire traceback error
        error_message = traceback.format_exc()
        return None, error_message

# Function to evaluate student responses
def evaluate_response(response, expected_output):
    # Capture the actual output
    actual_output, error = execute_code(response)

    # Determine correctness
    correct = (actual_output == expected_output)

    # Check efficiency (time taken)
    try:
        efficiency = timeit.timeit(lambda: exec(response, {}, {}), number=10)
    except:
        efficiency = float('inf')

    # Check best practices (PEP 8 compliance)
    formatted_code = autopep8.fix_code(response)
    pep8_compliance = response == formatted_code

    # Scoring
    score = 0
    if correct:
        score += 5
    if efficiency < 1:
        score += 3
    if pep8_compliance:
        score += 2

    # Generate feedback
    feedback = ""
    if correct:
        feedback += "Correct Answer. Well done!\n"
    else:
        feedback += "Incorrect Answer. Please review your logic.\n"

    if efficiency > 1:
        feedback += "Your code is inefficient. Consider optimizing it.\n"
    else:
        feedback += "Your code is efficient.\n"

    if not pep8_compliance:
        feedback += "Your code does not follow PEP 8 guidelines. Consider formatting it.\n"
    else:
        feedback += "Your code follows PEP 8 guidelines. Good job!\n"

    if error:
        feedback += f"Error encountered: \n{error}\n"

    return actual_output, correct, efficiency, pep8_compliance, score, feedback

# Process each student's response
results = []
for i in range(len(df)):
    for student in ['Student 1 Response', 'Student 2 Response']:
        response = df.loc[i, student]
        expected = expected_outputs[i]
        output, correct, efficiency, pep8, score, feedback = evaluate_response(response, expected)
        results.append([
            df.loc[i, 'Instruction'],
            student,
            response,
            expected,
            output,
            correct,
            round(efficiency, 4),
            pep8,
            score,
            feedback
        ])

# Save the results
results_df = pd.DataFrame(results, columns=[
    'Instruction', 'Student', 'Student Response', 'Expected Output', 'Actual Output',
    'Correct', 'Efficiency (s)', 'PEP 8 Compliant', 'Score (out of 10)', 'Feedback'
])

results_excel_path = '/content/drive/MyDrive/evaluation_results.xlsx'
results_df.to_excel(results_excel_path, index=False)

# Generate graphs
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

# Bar graph for Score Distribution
scores = results_df['Score (out of 10)']
axes[0].hist(scores, bins=10, color='skyblue', edgecolor='black')
axes[0].set_title('Score Distribution')
axes[0].set_xlabel('Score')
axes[0].set_ylabel('Number of Students')

# Line graph for Efficiency Comparison
axes[1].plot(results_df['Efficiency (s)'], marker='o', color='orange')
axes[1].set_title('Efficiency Comparison')
axes[1].set_xlabel('Student')
axes[1].set_ylabel('Execution Time (s)')

# Pie chart for Correct vs Incorrect Answers
correct_answers = sum(results_df['Correct'])
incorrect_answers = len(results_df) - correct_answers
axes[2].pie([correct_answers, incorrect_answers], labels=['Correct', 'Incorrect'], autopct='%1.1f%%', startangle=90, colors=['#4CAF50', '#FF5722'])
axes[2].set_title('Correct vs Incorrect Answers')

# Save the graph
graph_path = '/content/drive/MyDrive/evaluation_graphs.png'
plt.savefig(graph_path)

print(f"Evaluation completed successfully.")
print(f"Download the evaluation results from the link below:")
print(f"[Download evaluation_results.xlsx](sandbox:{results_excel_path})")
print(f"[Download evaluation_graphs.png](sandbox:{graph_path})")