# -*- coding: utf-8 -*-
"""MCQ Gamification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12fGYjm8VQXsmDGEgyOnhWZMrq0FIKZLg
"""

import pandas as pd
import os
import random
import time

# Define file paths
mcq_file = "/content/drive/MyDrive/Python_40_MCQ_Questions_Modified_Updated.xlsx"
student_file = "/content/drive/MyDrive/Kerala_Student_Records_Final.xlsx"
csv_file_path = "/content/drive/MyDrive/MCQ_Results_Updated_Cleaned_v3.csv"

# Define correct headers
expected_columns = ["Reg No.", "Name", "Score", "Low Level Score", "Medium Level Score", "High Level Score", "Unknown Level Score", "Feedback", "Badge", "Streak", "Previous Score", "Improvement"]

# Ensure CSV file is correctly formatted
if os.path.exists(csv_file_path):
    try:
        results_df = pd.read_csv(csv_file_path, dtype=str, engine="python")
        if not all(col in results_df.columns for col in expected_columns):
            results_df = results_df.reindex(columns=expected_columns, fill_value="")
            results_df.to_csv(csv_file_path, index=False)
        recorded_students = set(results_df["Reg No."].astype(str)) if not results_df.empty else set()
    except pd.errors.ParserError:
        results_df = pd.DataFrame(columns=expected_columns)
        results_df.to_csv(csv_file_path, index=False)
        recorded_students = set()
else:
    results_df = pd.DataFrame(columns=expected_columns)
    results_df.to_csv(csv_file_path, index=False)
    recorded_students = set()

# Load datasets
mcqs = pd.read_excel(mcq_file)
students = pd.read_excel(student_file)
students_dict = students.to_dict(orient="records")
mcqs_dict = mcqs.to_dict(orient="records")

# Define number of questions per level
QUESTIONS_PER_LEVEL = 5

# Function to select random questions
def select_questions(level):
    questions = [q for q in mcqs_dict if q.get("Level") == level]
    random.shuffle(questions)
    return questions[:QUESTIONS_PER_LEVEL]

# Function to evaluate the student
def evaluate_student(Reg_No, results_df):
    Reg_No = str(Reg_No).strip()
    prev_record = results_df[results_df["Reg No."] == Reg_No]
    is_first_attempt = Reg_No not in recorded_students
    previous_score = int(prev_record["Score"].values[0]) if not prev_record.empty and prev_record["Score"].values[0].isdigit() else 0

    # Fetch student details
    found_student = next((s for s in students_dict if str(s["Reg No."]) == Reg_No), None)
    if not found_student:
        print("❌ Student not found.")
        return

    print(f"\n👨‍🎓 Student: {found_student['Name']}")
    level_scores = {"Low": 0, "Medium": 0, "High": 0, "Unknown": 0}
    level_totals = {"Low": 0, "Medium": 0, "High": 0, "Unknown": 0}
    streak = 0

    current_level = "Low"
    total_questions_attempted = 0

    while current_level and total_questions_attempted < 15:
        selected_questions = select_questions(current_level)
        correct_count = 0
        total_count = len(selected_questions)

        for mcq in selected_questions:
            total_questions_attempted += 1

            level = mcq.get("Level", "Unknown")
            level_totals[level] += 1

            print("\n" + mcq["Question"])
            options = [mcq[col] for col in mcq.keys() if "Option" in col]
            for idx, option in enumerate(options, start=1):
                print(f"{idx}. {option}")

            correct_idx = int(str(mcq["Correct Answer"]).strip()) - 1
            answer_idx = None
            start_time = time.time()

            while time.time() - start_time < 15:
                try:
                    answer_idx = int(input(f"⏳ Enter your choice (1-{len(options)}): ")) - 1
                    if 0 <= answer_idx < len(options):
                        break
                except ValueError:
                    pass

            if answer_idx is None:
                print("⏰ Time's up! Moving to the next question.")
                continue

            if answer_idx == correct_idx:
                print("✅ Correct!")
                level_scores[level] += 1
                correct_count += 1
                streak += 1
            else:
                print(f"❌ Incorrect! Correct answer: {correct_idx + 1}")
                streak = 0

        accuracy = (correct_count / total_count) * 100 if total_count > 0 else 0

        # Continue only if score >= 50%
        if accuracy >= 50:
            if current_level == "Low":
                current_level = "Medium"
            elif current_level == "Medium":
                current_level = "High"
            elif current_level == "High":
                current_level = None
        else:
            current_level = None

    total_score = sum(level_scores.values())
    badge = "🏆 Python Pro" if total_score == 15 else "🌟 Python Enthusiast" if total_score >= 5 else "🚀 Keep Practicing"

    feedback = []
    for level in ["Low", "Medium", "High", "Unknown"]:
        if level_totals[level] > 0:
            accuracy = (level_scores[level] / level_totals[level]) * 100
            if accuracy >= 80:
                feedback.append(f"✅ Excellent at {level}-level questions.")
            elif accuracy >= 50:
                feedback.append(f"📘 Good at {level}-level questions but needs improvement.")
            else:
                feedback.append(f"❗ Weak at {level}-level questions. Needs practice.")

    feedback_text = " | ".join(feedback)
    improvement = "📈 Improved" if not is_first_attempt and total_score > previous_score else ""

    new_result = pd.DataFrame([{
        "Reg No.": Reg_No,
        "Name": found_student["Name"],
        "Score": total_score,
        "Low Level Score": level_scores["Low"],
        "Medium Level Score": level_scores["Medium"],
        "High Level Score": level_scores["High"],
        "Unknown Level Score": level_scores["Unknown"],
        "Feedback": feedback_text,
        "Badge": badge,
        "Streak": streak,
        "Previous Score": previous_score,
        "Improvement": improvement
    }])

    results_df = results_df[results_df["Reg No."] != Reg_No]
    results_df = pd.concat([results_df, new_result], ignore_index=True)
    results_df.to_csv(csv_file_path, index=False)
    print(f"\n📂 Score saved successfully! 🏅 Badge Earned: {badge}")

Reg_No = input("Enter Registration Number: ").strip()
evaluate_student(Reg_No, results_df) # Pass results_df to the function